CREATE TABLE `backload_state` (
	`resource` text PRIMARY KEY NOT NULL,
	`cursor` text,
	`status` text DEFAULT 'idle' NOT NULL,
	`last_synced_at` integer,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `charges` (
	`id` text PRIMARY KEY NOT NULL,
	`object` text,
	`amount` integer,
	`amount_captured` integer,
	`amount_refunded` integer,
	`application` text,
	`application_fee` text,
	`application_fee_amount` integer,
	`balance_transaction` text,
	`billing_details` text,
	`calculated_statement_descriptor` text,
	`captured` integer,
	`created` integer,
	`currency` text,
	`customer` text,
	`description` text,
	`destination` text,
	`disputed` integer,
	`failure_balance_transaction` text,
	`failure_code` text,
	`failure_message` text,
	`fraud_details` text,
	`livemode` integer,
	`metadata` text,
	`on_behalf_of` text,
	`order` text,
	`outcome` text,
	`paid` integer,
	`payment_intent` text,
	`payment_method` text,
	`payment_method_details` text,
	`radar_options` text,
	`receipt_email` text,
	`receipt_number` text,
	`receipt_url` text,
	`refunded` integer,
	`review` text,
	`shipping` text,
	`source_transfer` text,
	`statement_descriptor` text,
	`statement_descriptor_suffix` text,
	`status` text,
	`transfer_data` text,
	`transfer_group` text,
	`last_event_at` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_charges_customer` ON `charges` (`customer`);--> statement-breakpoint
CREATE INDEX `idx_charges_payment_intent` ON `charges` (`payment_intent`);--> statement-breakpoint
CREATE TABLE `customers` (
	`id` text PRIMARY KEY NOT NULL,
	`object` text,
	`address` text,
	`balance` integer,
	`created` integer,
	`currency` text,
	`default_source` text,
	`delinquent` integer,
	`description` text,
	`discount` text,
	`email` text,
	`invoice_prefix` text,
	`invoice_settings` text,
	`livemode` integer,
	`metadata` text,
	`name` text,
	`next_invoice_sequence` integer,
	`phone` text,
	`preferred_locales` text,
	`shipping` text,
	`tax_exempt` text,
	`test_clock` text,
	`deleted` integer,
	`last_event_at` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_customers_email` ON `customers` (`email`);--> statement-breakpoint
CREATE TABLE `invoice_line_items` (
	`id` text PRIMARY KEY NOT NULL,
	`object` text,
	`amount` integer,
	`currency` text,
	`description` text,
	`discount_amounts` text,
	`discountable` integer,
	`discounts` text,
	`invoice` text,
	`livemode` integer,
	`metadata` text,
	`parent` text,
	`period` text,
	`pretax_credit_amounts` text,
	`pricing` text,
	`quantity` integer,
	`quantity_decimal` text,
	`subscription` text,
	`subtotal` integer,
	`taxes` text,
	`last_event_at` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_invoice_line_items_invoice` ON `invoice_line_items` (`invoice`);--> statement-breakpoint
CREATE TABLE `invoices` (
	`id` text PRIMARY KEY NOT NULL,
	`object` text,
	`account_country` text,
	`account_name` text,
	`account_tax_ids` text,
	`amount_due` integer,
	`amount_overpaid` integer,
	`amount_paid` integer,
	`amount_paid_off_stripe` integer,
	`amount_remaining` integer,
	`amount_shipping` integer,
	`application` text,
	`attempt_count` integer,
	`attempted` integer,
	`auto_advance` integer,
	`automatic_tax` text,
	`automatically_finalizes_at` integer,
	`billing_reason` text,
	`collection_method` text,
	`created` integer,
	`currency` text,
	`custom_fields` text,
	`customer` text,
	`customer_account` text,
	`customer_address` text,
	`customer_email` text,
	`customer_name` text,
	`customer_phone` text,
	`customer_shipping` text,
	`customer_tax_exempt` text,
	`customer_tax_ids` text,
	`default_payment_method` text,
	`default_source` text,
	`default_tax_rates` text,
	`description` text,
	`discounts` text,
	`due_date` integer,
	`effective_at` integer,
	`ending_balance` integer,
	`footer` text,
	`from_invoice` text,
	`hosted_invoice_url` text,
	`invoice_pdf` text,
	`issuer` text,
	`last_finalization_error` text,
	`latest_revision` text,
	`livemode` integer,
	`metadata` text,
	`next_payment_attempt` integer,
	`number` text,
	`on_behalf_of` text,
	`parent` text,
	`payment_settings` text,
	`period_end` integer,
	`period_start` integer,
	`post_payment_credit_notes_amount` integer,
	`pre_payment_credit_notes_amount` integer,
	`receipt_number` text,
	`rendering` text,
	`shipping_cost` text,
	`shipping_details` text,
	`starting_balance` integer,
	`statement_descriptor` text,
	`status` text,
	`status_transitions` text,
	`subtotal` integer,
	`subtotal_excluding_tax` integer,
	`test_clock` text,
	`total` integer,
	`total_discount_amounts` text,
	`total_excluding_tax` integer,
	`total_pretax_credit_amounts` text,
	`total_taxes` text,
	`webhooks_delivered_at` integer,
	`last_event_at` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_invoices_customer` ON `invoices` (`customer`);--> statement-breakpoint
CREATE INDEX `idx_invoices_status` ON `invoices` (`status`);--> statement-breakpoint
CREATE TABLE `payment_intents` (
	`id` text PRIMARY KEY NOT NULL,
	`object` text,
	`amount` integer,
	`amount_capturable` integer,
	`amount_details` text,
	`amount_received` integer,
	`application` text,
	`application_fee_amount` integer,
	`automatic_payment_methods` text,
	`canceled_at` integer,
	`cancellation_reason` text,
	`capture_method` text,
	`client_secret` text,
	`confirmation_method` text,
	`created` integer,
	`currency` text,
	`customer` text,
	`description` text,
	`last_payment_error` text,
	`latest_charge` text,
	`livemode` integer,
	`metadata` text,
	`next_action` text,
	`on_behalf_of` text,
	`payment_method` text,
	`payment_method_configuration_details` text,
	`payment_method_options` text,
	`payment_method_types` text,
	`processing` text,
	`receipt_email` text,
	`review` text,
	`setup_future_usage` text,
	`shipping` text,
	`source` text,
	`statement_descriptor` text,
	`statement_descriptor_suffix` text,
	`status` text,
	`transfer_data` text,
	`transfer_group` text,
	`last_event_at` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_payment_intents_customer` ON `payment_intents` (`customer`);--> statement-breakpoint
CREATE TABLE `prices` (
	`id` text PRIMARY KEY NOT NULL,
	`object` text,
	`active` integer,
	`billing_scheme` text,
	`created` integer,
	`currency` text,
	`custom_unit_amount` text,
	`livemode` integer,
	`lookup_key` text,
	`metadata` text,
	`nickname` text,
	`product` text,
	`recurring` text,
	`tax_behavior` text,
	`tiers` text,
	`tiers_mode` text,
	`transform_quantity` text,
	`type` text,
	`unit_amount` integer,
	`unit_amount_decimal` text,
	`last_event_at` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_prices_product` ON `prices` (`product`);--> statement-breakpoint
CREATE TABLE `products` (
	`id` text PRIMARY KEY NOT NULL,
	`object` text,
	`active` integer,
	`created` integer,
	`default_price` text,
	`description` text,
	`images` text,
	`livemode` integer,
	`marketing_features` text,
	`metadata` text,
	`name` text,
	`package_dimensions` text,
	`shippable` integer,
	`statement_descriptor` text,
	`tax_code` text,
	`type` text,
	`unit_label` text,
	`updated` integer,
	`url` text,
	`last_event_at` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE `refunds` (
	`id` text PRIMARY KEY NOT NULL,
	`object` text,
	`amount` integer,
	`balance_transaction` text,
	`charge` text,
	`created` integer,
	`currency` text,
	`destination_details` text,
	`failure_balance_transaction` text,
	`failure_reason` text,
	`instructions_email` text,
	`metadata` text,
	`next_action` text,
	`payment_intent` text,
	`reason` text,
	`receipt_number` text,
	`source_transfer_reversal` text,
	`status` text,
	`transfer_reversal` text,
	`last_event_at` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_refunds_charge` ON `refunds` (`charge`);--> statement-breakpoint
CREATE INDEX `idx_refunds_payment_intent` ON `refunds` (`payment_intent`);--> statement-breakpoint
CREATE TABLE `stripe_events` (
	`id` text PRIMARY KEY NOT NULL,
	`type` text NOT NULL,
	`api_version` text,
	`request_id` text,
	`created` integer NOT NULL,
	`payload` text NOT NULL,
	`received_at` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_stripe_events_type_created` ON `stripe_events` (`type`,`created`);--> statement-breakpoint
CREATE TABLE `subscription_items` (
	`id` text PRIMARY KEY NOT NULL,
	`object` text,
	`billed_until` integer,
	`billing_thresholds` text,
	`created` integer,
	`current_period_end` integer,
	`current_period_start` integer,
	`discounts` text,
	`metadata` text,
	`price` text,
	`quantity` integer,
	`subscription` text,
	`tax_rates` text,
	`last_event_at` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_subscription_items_subscription` ON `subscription_items` (`subscription`);--> statement-breakpoint
CREATE INDEX `idx_subscription_items_price` ON `subscription_items` (`price`);--> statement-breakpoint
CREATE TABLE `subscriptions` (
	`id` text PRIMARY KEY NOT NULL,
	`object` text,
	`application` text,
	`application_fee_percent` real,
	`automatic_tax` text,
	`billing_cycle_anchor` integer,
	`billing_cycle_anchor_config` text,
	`billing_mode` text,
	`billing_schedules` text,
	`billing_thresholds` text,
	`cancel_at` integer,
	`cancel_at_period_end` integer,
	`canceled_at` integer,
	`cancellation_details` text,
	`collection_method` text,
	`created` integer,
	`currency` text,
	`customer` text,
	`customer_account` text,
	`days_until_due` integer,
	`default_payment_method` text,
	`default_source` text,
	`default_tax_rates` text,
	`description` text,
	`discounts` text,
	`ended_at` integer,
	`invoice_settings` text,
	`latest_invoice` text,
	`livemode` integer,
	`managed_payments` text,
	`metadata` text,
	`next_pending_invoice_item_invoice` integer,
	`on_behalf_of` text,
	`pause_collection` text,
	`payment_settings` text,
	`pending_invoice_item_interval` text,
	`pending_setup_intent` text,
	`pending_update` text,
	`presentment_details` text,
	`schedule` text,
	`start_date` integer,
	`status` text,
	`test_clock` text,
	`transfer_data` text,
	`trial_end` integer,
	`trial_settings` text,
	`trial_start` integer,
	`last_event_at` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_subscriptions_customer` ON `subscriptions` (`customer`);--> statement-breakpoint
CREATE INDEX `idx_subscriptions_status` ON `subscriptions` (`status`);