import { sqliteTable, text, integer, real, index } from 'drizzle-orm/sqlite-core';

export const stripeEvents = sqliteTable(
  'stripe_events',
  {
    id: text('id').primaryKey(),
    type: text('type').notNull(),
    apiVersion: text('api_version'),
    requestId: text('request_id'),
    created: integer('created').notNull(),
    payload: text('payload', { mode: 'json' }).notNull(),
    receivedAt: integer('received_at').notNull(),
  },
  (t) => ({ typeCreatedIdx: index('idx_stripe_events_type_created').on(t.type, t.created) }),
);

export const backloadState = sqliteTable('backload_state', {
  resource: text('resource').primaryKey(),
  cursor: text('cursor'),
  status: text('status', { enum: ['idle', 'in_progress', 'done'] }).notNull().default('idle'),
  lastSyncedAt: integer('last_synced_at'),
  updatedAt: integer('updated_at').notNull(),
});

export const customers = sqliteTable(
  'customers',
  {
    id: text('id').primaryKey(),
    object: text('object'),
    address: text('address', { mode: 'json' }),
    balance: integer('balance'),
    created: integer('created'),
    currency: text('currency'),
    defaultSource: text('default_source'),
    delinquent: integer('delinquent', { mode: 'boolean' }),
    description: text('description'),
    discount: text('discount', { mode: 'json' }),
    email: text('email'),
    invoicePrefix: text('invoice_prefix'),
    invoiceSettings: text('invoice_settings', { mode: 'json' }),
    livemode: integer('livemode', { mode: 'boolean' }),
    metadata: text('metadata', { mode: 'json' }),
    name: text('name'),
    nextInvoiceSequence: integer('next_invoice_sequence'),
    phone: text('phone'),
    preferredLocales: text('preferred_locales', { mode: 'json' }),
    shipping: text('shipping', { mode: 'json' }),
    taxExempt: text('tax_exempt'),
    testClock: text('test_clock'),
    deleted: integer('deleted', { mode: 'boolean' }),
    lastEventAt: integer('last_event_at').notNull().default(0),
  },
  (t) => ({ emailIdx: index('idx_customers_email').on(t.email) }),
);

export const products = sqliteTable('products', {
  id: text('id').primaryKey(),
  object: text('object'),
  active: integer('active', { mode: 'boolean' }),
  created: integer('created'),
  defaultPrice: text('default_price'),
  description: text('description'),
  images: text('images', { mode: 'json' }),
  livemode: integer('livemode', { mode: 'boolean' }),
  marketingFeatures: text('marketing_features', { mode: 'json' }),
  metadata: text('metadata', { mode: 'json' }),
  name: text('name'),
  packageDimensions: text('package_dimensions', { mode: 'json' }),
  shippable: integer('shippable', { mode: 'boolean' }),
  statementDescriptor: text('statement_descriptor'),
  taxCode: text('tax_code'),
  type: text('type'),
  unitLabel: text('unit_label'),
  updated: integer('updated'),
  url: text('url'),
  lastEventAt: integer('last_event_at').notNull().default(0),
});

export const prices = sqliteTable(
  'prices',
  {
    id: text('id').primaryKey(),
    object: text('object'),
    active: integer('active', { mode: 'boolean' }),
    billingScheme: text('billing_scheme'),
    created: integer('created'),
    currency: text('currency'),
    customUnitAmount: text('custom_unit_amount', { mode: 'json' }),
    livemode: integer('livemode', { mode: 'boolean' }),
    lookupKey: text('lookup_key'),
    metadata: text('metadata', { mode: 'json' }),
    nickname: text('nickname'),
    product: text('product'),
    recurring: text('recurring', { mode: 'json' }),
    taxBehavior: text('tax_behavior'),
    tiers: text('tiers', { mode: 'json' }),
    tiersMode: text('tiers_mode'),
    transformQuantity: text('transform_quantity', { mode: 'json' }),
    type: text('type'),
    unitAmount: integer('unit_amount'),
    unitAmountDecimal: text('unit_amount_decimal'),
    lastEventAt: integer('last_event_at').notNull().default(0),
  },
  (t) => ({ productIdx: index('idx_prices_product').on(t.product) }),
);

export const subscriptions = sqliteTable(
  'subscriptions',
  {
    id: text('id').primaryKey(),
    object: text('object'),
    application: text('application'),
    applicationFeePercent: real('application_fee_percent'),
    automaticTax: text('automatic_tax', { mode: 'json' }),
    billingCycleAnchor: integer('billing_cycle_anchor'),
    billingCycleAnchorConfig: text('billing_cycle_anchor_config', { mode: 'json' }),
    billingMode: text('billing_mode', { mode: 'json' }),
    billingSchedules: text('billing_schedules', { mode: 'json' }),
    billingThresholds: text('billing_thresholds', { mode: 'json' }),
    cancelAt: integer('cancel_at'),
    cancelAtPeriodEnd: integer('cancel_at_period_end', { mode: 'boolean' }),
    canceledAt: integer('canceled_at'),
    cancellationDetails: text('cancellation_details', { mode: 'json' }),
    collectionMethod: text('collection_method'),
    created: integer('created'),
    currency: text('currency'),
    customer: text('customer'),
    customerAccount: text('customer_account'),
    daysUntilDue: integer('days_until_due'),
    defaultPaymentMethod: text('default_payment_method'),
    defaultSource: text('default_source'),
    defaultTaxRates: text('default_tax_rates', { mode: 'json' }),
    description: text('description'),
    discounts: text('discounts', { mode: 'json' }),
    endedAt: integer('ended_at'),
    invoiceSettings: text('invoice_settings', { mode: 'json' }),
    latestInvoice: text('latest_invoice'),
    livemode: integer('livemode', { mode: 'boolean' }),
    managedPayments: text('managed_payments', { mode: 'json' }),
    metadata: text('metadata', { mode: 'json' }),
    nextPendingInvoiceItemInvoice: integer('next_pending_invoice_item_invoice'),
    onBehalfOf: text('on_behalf_of'),
    pauseCollection: text('pause_collection', { mode: 'json' }),
    paymentSettings: text('payment_settings', { mode: 'json' }),
    pendingInvoiceItemInterval: text('pending_invoice_item_interval', { mode: 'json' }),
    pendingSetupIntent: text('pending_setup_intent'),
    pendingUpdate: text('pending_update', { mode: 'json' }),
    presentmentDetails: text('presentment_details', { mode: 'json' }),
    schedule: text('schedule'),
    startDate: integer('start_date'),
    status: text('status'),
    testClock: text('test_clock'),
    transferData: text('transfer_data', { mode: 'json' }),
    trialEnd: integer('trial_end'),
    trialSettings: text('trial_settings', { mode: 'json' }),
    trialStart: integer('trial_start'),
    lastEventAt: integer('last_event_at').notNull().default(0),
  },
  (t) => ({
    customerIdx: index('idx_subscriptions_customer').on(t.customer),
    statusIdx: index('idx_subscriptions_status').on(t.status),
  }),
);

export const subscriptionItems = sqliteTable(
  'subscription_items',
  {
    id: text('id').primaryKey(),
    object: text('object'),
    billedUntil: integer('billed_until'),
    billingThresholds: text('billing_thresholds', { mode: 'json' }),
    created: integer('created'),
    currentPeriodEnd: integer('current_period_end'),
    currentPeriodStart: integer('current_period_start'),
    discounts: text('discounts', { mode: 'json' }),
    metadata: text('metadata', { mode: 'json' }),
    price: text('price'),
    quantity: integer('quantity'),
    subscription: text('subscription'),
    taxRates: text('tax_rates', { mode: 'json' }),
    lastEventAt: integer('last_event_at').notNull().default(0),
  },
  (t) => ({
    subscriptionIdx: index('idx_subscription_items_subscription').on(t.subscription),
    priceIdx: index('idx_subscription_items_price').on(t.price),
  }),
);

export const invoices = sqliteTable(
  'invoices',
  {
    id: text('id').primaryKey(),
    object: text('object'),
    accountCountry: text('account_country'),
    accountName: text('account_name'),
    accountTaxIds: text('account_tax_ids', { mode: 'json' }),
    amountDue: integer('amount_due'),
    amountOverpaid: integer('amount_overpaid'),
    amountPaid: integer('amount_paid'),
    amountPaidOffStripe: integer('amount_paid_off_stripe'),
    amountRemaining: integer('amount_remaining'),
    amountShipping: integer('amount_shipping'),
    application: text('application'),
    attemptCount: integer('attempt_count'),
    attempted: integer('attempted', { mode: 'boolean' }),
    autoAdvance: integer('auto_advance', { mode: 'boolean' }),
    automaticTax: text('automatic_tax', { mode: 'json' }),
    automaticallyFinalizesAt: integer('automatically_finalizes_at'),
    billingReason: text('billing_reason'),
    collectionMethod: text('collection_method'),
    created: integer('created'),
    currency: text('currency'),
    customFields: text('custom_fields', { mode: 'json' }),
    customer: text('customer'),
    customerAccount: text('customer_account'),
    customerAddress: text('customer_address', { mode: 'json' }),
    customerEmail: text('customer_email'),
    customerName: text('customer_name'),
    customerPhone: text('customer_phone'),
    customerShipping: text('customer_shipping', { mode: 'json' }),
    customerTaxExempt: text('customer_tax_exempt'),
    customerTaxIds: text('customer_tax_ids', { mode: 'json' }),
    defaultPaymentMethod: text('default_payment_method'),
    defaultSource: text('default_source'),
    defaultTaxRates: text('default_tax_rates', { mode: 'json' }),
    description: text('description'),
    discounts: text('discounts', { mode: 'json' }),
    dueDate: integer('due_date'),
    effectiveAt: integer('effective_at'),
    endingBalance: integer('ending_balance'),
    footer: text('footer'),
    fromInvoice: text('from_invoice', { mode: 'json' }),
    hostedInvoiceUrl: text('hosted_invoice_url'),
    invoicePdf: text('invoice_pdf'),
    issuer: text('issuer', { mode: 'json' }),
    lastFinalizationError: text('last_finalization_error', { mode: 'json' }),
    latestRevision: text('latest_revision'),
    livemode: integer('livemode', { mode: 'boolean' }),
    metadata: text('metadata', { mode: 'json' }),
    nextPaymentAttempt: integer('next_payment_attempt'),
    number: text('number'),
    onBehalfOf: text('on_behalf_of'),
    parent: text('parent', { mode: 'json' }),
    paymentSettings: text('payment_settings', { mode: 'json' }),
    periodEnd: integer('period_end'),
    periodStart: integer('period_start'),
    postPaymentCreditNotesAmount: integer('post_payment_credit_notes_amount'),
    prePaymentCreditNotesAmount: integer('pre_payment_credit_notes_amount'),
    receiptNumber: text('receipt_number'),
    rendering: text('rendering', { mode: 'json' }),
    shippingCost: text('shipping_cost', { mode: 'json' }),
    shippingDetails: text('shipping_details', { mode: 'json' }),
    startingBalance: integer('starting_balance'),
    statementDescriptor: text('statement_descriptor'),
    status: text('status'),
    statusTransitions: text('status_transitions', { mode: 'json' }),
    subtotal: integer('subtotal'),
    subtotalExcludingTax: integer('subtotal_excluding_tax'),
    testClock: text('test_clock'),
    total: integer('total'),
    totalDiscountAmounts: text('total_discount_amounts', { mode: 'json' }),
    totalExcludingTax: integer('total_excluding_tax'),
    totalPretaxCreditAmounts: text('total_pretax_credit_amounts', { mode: 'json' }),
    totalTaxes: text('total_taxes', { mode: 'json' }),
    webhooksDeliveredAt: integer('webhooks_delivered_at'),
    lastEventAt: integer('last_event_at').notNull().default(0),
  },
  (t) => ({
    customerIdx: index('idx_invoices_customer').on(t.customer),
    statusIdx: index('idx_invoices_status').on(t.status),
  }),
);

export const invoiceLineItems = sqliteTable(
  'invoice_line_items',
  {
    id: text('id').primaryKey(),
    object: text('object'),
    amount: integer('amount'),
    currency: text('currency'),
    description: text('description'),
    discountAmounts: text('discount_amounts', { mode: 'json' }),
    discountable: integer('discountable', { mode: 'boolean' }),
    discounts: text('discounts', { mode: 'json' }),
    invoice: text('invoice'),
    livemode: integer('livemode', { mode: 'boolean' }),
    metadata: text('metadata', { mode: 'json' }),
    parent: text('parent', { mode: 'json' }),
    period: text('period', { mode: 'json' }),
    pretaxCreditAmounts: text('pretax_credit_amounts', { mode: 'json' }),
    pricing: text('pricing', { mode: 'json' }),
    quantity: integer('quantity'),
    quantityDecimal: text('quantity_decimal'),
    subscription: text('subscription'),
    subtotal: integer('subtotal'),
    taxes: text('taxes', { mode: 'json' }),
    lastEventAt: integer('last_event_at').notNull().default(0),
  },
  (t) => ({ invoiceIdx: index('idx_invoice_line_items_invoice').on(t.invoice) }),
);

export const charges = sqliteTable(
  'charges',
  {
    id: text('id').primaryKey(),
    object: text('object'),
    amount: integer('amount'),
    amountCaptured: integer('amount_captured'),
    amountRefunded: integer('amount_refunded'),
    application: text('application'),
    applicationFee: text('application_fee'),
    applicationFeeAmount: integer('application_fee_amount'),
    balanceTransaction: text('balance_transaction'),
    billingDetails: text('billing_details', { mode: 'json' }),
    calculatedStatementDescriptor: text('calculated_statement_descriptor'),
    captured: integer('captured', { mode: 'boolean' }),
    created: integer('created'),
    currency: text('currency'),
    customer: text('customer'),
    description: text('description'),
    destination: text('destination'),
    disputed: integer('disputed', { mode: 'boolean' }),
    failureBalanceTransaction: text('failure_balance_transaction'),
    failureCode: text('failure_code'),
    failureMessage: text('failure_message'),
    fraudDetails: text('fraud_details', { mode: 'json' }),
    livemode: integer('livemode', { mode: 'boolean' }),
    metadata: text('metadata', { mode: 'json' }),
    onBehalfOf: text('on_behalf_of'),
    order: text('order'),
    outcome: text('outcome', { mode: 'json' }),
    paid: integer('paid', { mode: 'boolean' }),
    paymentIntent: text('payment_intent'),
    paymentMethod: text('payment_method'),
    paymentMethodDetails: text('payment_method_details', { mode: 'json' }),
    radarOptions: text('radar_options', { mode: 'json' }),
    receiptEmail: text('receipt_email'),
    receiptNumber: text('receipt_number'),
    receiptUrl: text('receipt_url'),
    refunded: integer('refunded', { mode: 'boolean' }),
    review: text('review'),
    shipping: text('shipping', { mode: 'json' }),
    sourceTransfer: text('source_transfer'),
    statementDescriptor: text('statement_descriptor'),
    statementDescriptorSuffix: text('statement_descriptor_suffix'),
    status: text('status'),
    transferData: text('transfer_data', { mode: 'json' }),
    transferGroup: text('transfer_group'),
    lastEventAt: integer('last_event_at').notNull().default(0),
  },
  (t) => ({
    customerIdx: index('idx_charges_customer').on(t.customer),
    paymentIntentIdx: index('idx_charges_payment_intent').on(t.paymentIntent),
  }),
);

export const paymentIntents = sqliteTable(
  'payment_intents',
  {
    id: text('id').primaryKey(),
    object: text('object'),
    amount: integer('amount'),
    amountCapturable: integer('amount_capturable'),
    amountDetails: text('amount_details', { mode: 'json' }),
    amountReceived: integer('amount_received'),
    application: text('application'),
    applicationFeeAmount: integer('application_fee_amount'),
    automaticPaymentMethods: text('automatic_payment_methods', { mode: 'json' }),
    canceledAt: integer('canceled_at'),
    cancellationReason: text('cancellation_reason'),
    captureMethod: text('capture_method'),
    clientSecret: text('client_secret'),
    confirmationMethod: text('confirmation_method'),
    created: integer('created'),
    currency: text('currency'),
    customer: text('customer'),
    description: text('description'),
    lastPaymentError: text('last_payment_error', { mode: 'json' }),
    latestCharge: text('latest_charge'),
    livemode: integer('livemode', { mode: 'boolean' }),
    metadata: text('metadata', { mode: 'json' }),
    nextAction: text('next_action', { mode: 'json' }),
    onBehalfOf: text('on_behalf_of'),
    paymentMethod: text('payment_method'),
    paymentMethodConfigurationDetails: text('payment_method_configuration_details', { mode: 'json' }),
    paymentMethodOptions: text('payment_method_options', { mode: 'json' }),
    paymentMethodTypes: text('payment_method_types', { mode: 'json' }),
    processing: text('processing', { mode: 'json' }),
    receiptEmail: text('receipt_email'),
    review: text('review'),
    setupFutureUsage: text('setup_future_usage'),
    shipping: text('shipping', { mode: 'json' }),
    source: text('source'),
    statementDescriptor: text('statement_descriptor'),
    statementDescriptorSuffix: text('statement_descriptor_suffix'),
    status: text('status'),
    transferData: text('transfer_data', { mode: 'json' }),
    transferGroup: text('transfer_group'),
    lastEventAt: integer('last_event_at').notNull().default(0),
  },
  (t) => ({ customerIdx: index('idx_payment_intents_customer').on(t.customer) }),
);

export const refunds = sqliteTable(
  'refunds',
  {
    id: text('id').primaryKey(),
    object: text('object'),
    amount: integer('amount'),
    balanceTransaction: text('balance_transaction'),
    charge: text('charge'),
    created: integer('created'),
    currency: text('currency'),
    destinationDetails: text('destination_details', { mode: 'json' }),
    failureBalanceTransaction: text('failure_balance_transaction'),
    failureReason: text('failure_reason'),
    instructionsEmail: text('instructions_email'),
    metadata: text('metadata', { mode: 'json' }),
    nextAction: text('next_action', { mode: 'json' }),
    paymentIntent: text('payment_intent'),
    reason: text('reason'),
    receiptNumber: text('receipt_number'),
    sourceTransferReversal: text('source_transfer_reversal'),
    status: text('status'),
    transferReversal: text('transfer_reversal'),
    lastEventAt: integer('last_event_at').notNull().default(0),
  },
  (t) => ({
    chargeIdx: index('idx_refunds_charge').on(t.charge),
    paymentIntentIdx: index('idx_refunds_payment_intent').on(t.paymentIntent),
  }),
);
