import { sqliteTable, text, integer, real, index } from 'drizzle-orm/sqlite-core';

export const stripeEvents = sqliteTable(
  'stripe_events',
  {
    id: text('id').primaryKey(),
    type: text('type').notNull(),
    apiVersion: text('api_version'),
    requestId: text('request_id'),
    created: integer('created').notNull(),
    payload: text('payload', { mode: 'json' }).notNull(),
    receivedAt: integer('received_at').notNull(),
  },
  (t) => ({ typeCreatedIdx: index('idx_stripe_events_type_created').on(t.type, t.created) }),
);

export const backloadState = sqliteTable('backload_state', {
  resource: text('resource').primaryKey(),
  cursor: text('cursor'),
  status: text('status', { enum: ['idle', 'in_progress', 'done'] }).notNull().default('idle'),
  lastSyncedAt: integer('last_synced_at'),
  updatedAt: integer('updated_at').notNull(),
});

export const customers = sqliteTable(
  'customers',
  {
    id: text('id').primaryKey(),
    object: text('object'),
    address: text('address', { mode: 'json' }),
    balance: integer('balance'),
    created: integer('created'),
    currency: text('currency'),
    defaultSource: text('default_source'),
    delinquent: integer('delinquent', { mode: 'boolean' }),
    description: text('description'),
    discount: text('discount', { mode: 'json' }),
    email: text('email'),
    invoicePrefix: text('invoice_prefix'),
    invoiceSettings: text('invoice_settings', { mode: 'json' }),
    livemode: integer('livemode', { mode: 'boolean' }),
    metadata: text('metadata', { mode: 'json' }),
    name: text('name'),
    nextInvoiceSequence: integer('next_invoice_sequence'),
    phone: text('phone'),
    preferredLocales: text('preferred_locales', { mode: 'json' }),
    shipping: text('shipping', { mode: 'json' }),
    taxExempt: text('tax_exempt'),
    testClock: text('test_clock'),
    deleted: integer('deleted', { mode: 'boolean' }),
    lastEventAt: integer('last_event_at').notNull().default(0),
  },
  (t) => ({ emailIdx: index('idx_customers_email').on(t.email) }),
);

export const products = sqliteTable('products', {
  id: text('id').primaryKey(),
  object: text('object'),
  active: integer('active', { mode: 'boolean' }),
  attributes: text('attributes', { mode: 'json' }),
  created: integer('created'),
  defaultPrice: text('default_price'),
  description: text('description'),
  images: text('images', { mode: 'json' }),
  livemode: integer('livemode', { mode: 'boolean' }),
  metadata: text('metadata', { mode: 'json' }),
  name: text('name'),
  packageDimensions: text('package_dimensions', { mode: 'json' }),
  shippable: integer('shippable', { mode: 'boolean' }),
  statementDescriptor: text('statement_descriptor'),
  taxCode: text('tax_code'),
  type: text('type'),
  unitLabel: text('unit_label'),
  updated: integer('updated'),
  url: text('url'),
  lastEventAt: integer('last_event_at').notNull().default(0),
});

export const prices = sqliteTable(
  'prices',
  {
    id: text('id').primaryKey(),
    object: text('object'),
    active: integer('active', { mode: 'boolean' }),
    billingScheme: text('billing_scheme'),
    created: integer('created'),
    currency: text('currency'),
    customUnitAmount: text('custom_unit_amount', { mode: 'json' }),
    livemode: integer('livemode', { mode: 'boolean' }),
    lookupKey: text('lookup_key'),
    metadata: text('metadata', { mode: 'json' }),
    nickname: text('nickname'),
    product: text('product'),
    recurring: text('recurring', { mode: 'json' }),
    taxBehavior: text('tax_behavior'),
    tiers: text('tiers', { mode: 'json' }),
    tiersMode: text('tiers_mode'),
    transformQuantity: text('transform_quantity', { mode: 'json' }),
    type: text('type'),
    unitAmount: integer('unit_amount'),
    unitAmountDecimal: text('unit_amount_decimal'),
    lastEventAt: integer('last_event_at').notNull().default(0),
  },
  (t) => ({ productIdx: index('idx_prices_product').on(t.product) }),
);

export const subscriptions = sqliteTable(
  'subscriptions',
  {
    id: text('id').primaryKey(),
    object: text('object'),
    application: text('application'),
    applicationFeePercent: real('application_fee_percent'),
    automaticTax: text('automatic_tax', { mode: 'json' }),
    billingCycleAnchor: integer('billing_cycle_anchor'),
    billingThresholds: text('billing_thresholds', { mode: 'json' }),
    cancelAt: integer('cancel_at'),
    cancelAtPeriodEnd: integer('cancel_at_period_end', { mode: 'boolean' }),
    canceledAt: integer('canceled_at'),
    cancellationDetails: text('cancellation_details', { mode: 'json' }),
    collectionMethod: text('collection_method'),
    created: integer('created'),
    currency: text('currency'),
    currentPeriodEnd: integer('current_period_end'),
    currentPeriodStart: integer('current_period_start'),
    customer: text('customer'),
    daysUntilDue: integer('days_until_due'),
    defaultPaymentMethod: text('default_payment_method'),
    defaultSource: text('default_source'),
    defaultTaxRates: text('default_tax_rates', { mode: 'json' }),
    description: text('description'),
    discount: text('discount', { mode: 'json' }),
    endedAt: integer('ended_at'),
    latestInvoice: text('latest_invoice'),
    livemode: integer('livemode', { mode: 'boolean' }),
    metadata: text('metadata', { mode: 'json' }),
    nextPendingInvoiceItemInvoice: integer('next_pending_invoice_item_invoice'),
    onBehalfOf: text('on_behalf_of'),
    pauseCollection: text('pause_collection', { mode: 'json' }),
    paymentSettings: text('payment_settings', { mode: 'json' }),
    pendingInvoiceItemInterval: text('pending_invoice_item_interval', { mode: 'json' }),
    pendingSetupIntent: text('pending_setup_intent'),
    pendingUpdate: text('pending_update', { mode: 'json' }),
    schedule: text('schedule'),
    startDate: integer('start_date'),
    status: text('status'),
    testClock: text('test_clock'),
    transferData: text('transfer_data', { mode: 'json' }),
    trialEnd: integer('trial_end'),
    trialSettings: text('trial_settings', { mode: 'json' }),
    trialStart: integer('trial_start'),
    lastEventAt: integer('last_event_at').notNull().default(0),
  },
  (t) => ({
    customerIdx: index('idx_subscriptions_customer').on(t.customer),
    statusIdx: index('idx_subscriptions_status').on(t.status),
  }),
);

export const subscriptionItems = sqliteTable(
  'subscription_items',
  {
    id: text('id').primaryKey(),
    object: text('object'),
    billingThresholds: text('billing_thresholds', { mode: 'json' }),
    created: integer('created'),
    metadata: text('metadata', { mode: 'json' }),
    price: text('price'),
    quantity: integer('quantity'),
    subscription: text('subscription'),
    taxRates: text('tax_rates', { mode: 'json' }),
    lastEventAt: integer('last_event_at').notNull().default(0),
  },
  (t) => ({
    subscriptionIdx: index('idx_subscription_items_subscription').on(t.subscription),
    priceIdx: index('idx_subscription_items_price').on(t.price),
  }),
);
