import type Stripe from 'stripe';
import { sql } from 'drizzle-orm';
import type { DB } from '../db/client';
import { charges } from '../db/schema';

const strOrNull = (v: unknown): string | null => (typeof v === 'string' ? v : null);

export async function upsertCharge(
  db: DB,
  charge: Stripe.Charge,
  eventCreated: number,
): Promise<void> {
  // SDK types target the latest Stripe API; we mirror the 2024-10-28.acacia
  // shape (per sync-engine), so widen for field access.
  const c = charge as Stripe.Charge & Record<string, any>;
  const row = {
    id: c.id,
    object: c.object,
    amount: c.amount,
    amountCaptured: c.amount_captured,
    amountRefunded: c.amount_refunded,
    application: strOrNull(c.application),
    applicationFee: strOrNull(c.application_fee),
    applicationFeeAmount: c.application_fee_amount ?? null,
    balanceTransaction: strOrNull(c.balance_transaction),
    billingDetails: c.billing_details ?? null,
    calculatedStatementDescriptor: c.calculated_statement_descriptor ?? null,
    captured: c.captured,
    created: c.created,
    currency: c.currency,
    customer: strOrNull(c.customer),
    description: c.description ?? null,
    destination: strOrNull((c as any).destination),
    dispute: strOrNull(c.dispute),
    disputed: c.disputed,
    failureBalanceTransaction: strOrNull(c.failure_balance_transaction),
    failureCode: c.failure_code ?? null,
    failureMessage: c.failure_message ?? null,
    fraudDetails: c.fraud_details ?? null,
    invoice: strOrNull(c.invoice),
    livemode: c.livemode,
    metadata: c.metadata ?? null,
    onBehalfOf: strOrNull(c.on_behalf_of),
    order: strOrNull((c as any).order),
    outcome: c.outcome ?? null,
    paid: c.paid,
    paymentIntent: strOrNull(c.payment_intent),
    paymentMethod: c.payment_method ?? null,
    paymentMethodDetails: c.payment_method_details ?? null,
    radarOptions: c.radar_options ?? null,
    receiptEmail: c.receipt_email ?? null,
    receiptNumber: c.receipt_number ?? null,
    receiptUrl: c.receipt_url ?? null,
    refunded: c.refunded,
    review: strOrNull(c.review),
    shipping: c.shipping ?? null,
    sourceTransfer: strOrNull(c.source_transfer),
    statementDescriptor: c.statement_descriptor ?? null,
    statementDescriptorSuffix: c.statement_descriptor_suffix ?? null,
    status: c.status,
    transferData: c.transfer_data ?? null,
    transferGroup: c.transfer_group ?? null,
    lastEventAt: eventCreated,
  };

  await db.insert(charges).values(row).onConflictDoUpdate({
    target: charges.id,
    set: {
      object: sql`excluded.object`,
      amount: sql`excluded.amount`,
      amountCaptured: sql`excluded.amount_captured`,
      amountRefunded: sql`excluded.amount_refunded`,
      application: sql`excluded.application`,
      applicationFee: sql`excluded.application_fee`,
      applicationFeeAmount: sql`excluded.application_fee_amount`,
      balanceTransaction: sql`excluded.balance_transaction`,
      billingDetails: sql`excluded.billing_details`,
      calculatedStatementDescriptor: sql`excluded.calculated_statement_descriptor`,
      captured: sql`excluded.captured`,
      created: sql`excluded.created`,
      currency: sql`excluded.currency`,
      customer: sql`excluded.customer`,
      description: sql`excluded.description`,
      destination: sql`excluded.destination`,
      dispute: sql`excluded.dispute`,
      disputed: sql`excluded.disputed`,
      failureBalanceTransaction: sql`excluded.failure_balance_transaction`,
      failureCode: sql`excluded.failure_code`,
      failureMessage: sql`excluded.failure_message`,
      fraudDetails: sql`excluded.fraud_details`,
      invoice: sql`excluded.invoice`,
      livemode: sql`excluded.livemode`,
      metadata: sql`excluded.metadata`,
      onBehalfOf: sql`excluded.on_behalf_of`,
      order: sql`excluded."order"`,
      outcome: sql`excluded.outcome`,
      paid: sql`excluded.paid`,
      paymentIntent: sql`excluded.payment_intent`,
      paymentMethod: sql`excluded.payment_method`,
      paymentMethodDetails: sql`excluded.payment_method_details`,
      radarOptions: sql`excluded.radar_options`,
      receiptEmail: sql`excluded.receipt_email`,
      receiptNumber: sql`excluded.receipt_number`,
      receiptUrl: sql`excluded.receipt_url`,
      refunded: sql`excluded.refunded`,
      review: sql`excluded.review`,
      shipping: sql`excluded.shipping`,
      sourceTransfer: sql`excluded.source_transfer`,
      statementDescriptor: sql`excluded.statement_descriptor`,
      statementDescriptorSuffix: sql`excluded.statement_descriptor_suffix`,
      status: sql`excluded.status`,
      transferData: sql`excluded.transfer_data`,
      transferGroup: sql`excluded.transfer_group`,
      lastEventAt: sql`excluded.last_event_at`,
    },
    setWhere: sql`charges.last_event_at < ${eventCreated}`,
  });
}
