import type Stripe from 'stripe';
import { sql } from 'drizzle-orm';
import type { DB } from '../db/client';
import { invoices, invoiceLineItems } from '../db/schema';

const strOrNull = (v: unknown): string | null => (typeof v === 'string' ? v : null);

export async function upsertInvoice(
  db: DB,
  inv: Stripe.Invoice,
  eventCreated: number,
): Promise<void> {
  const customerId = typeof inv.customer === 'string' ? inv.customer : inv.customer?.id ?? null;

  const row = {
    id: inv.id,
    object: inv.object,
    accountCountry: inv.account_country ?? null,
    accountName: inv.account_name ?? null,
    accountTaxIds: inv.account_tax_ids ?? null,
    amountDue: inv.amount_due,
    amountPaid: inv.amount_paid,
    amountRemaining: inv.amount_remaining,
    amountShipping: inv.amount_shipping ?? null,
    application: strOrNull(inv.application),
    applicationFeeAmount: inv.application_fee_amount ?? null,
    attemptCount: inv.attempt_count,
    attempted: inv.attempted,
    autoAdvance: inv.auto_advance ?? null,
    automaticTax: inv.automatic_tax ?? null,
    billingReason: inv.billing_reason ?? null,
    charge: strOrNull(inv.charge),
    collectionMethod: inv.collection_method,
    created: inv.created,
    currency: inv.currency,
    customFields: inv.custom_fields ?? null,
    customer: customerId,
    customerAddress: inv.customer_address ?? null,
    customerEmail: inv.customer_email ?? null,
    customerName: inv.customer_name ?? null,
    customerPhone: inv.customer_phone ?? null,
    customerShipping: inv.customer_shipping ?? null,
    customerTaxExempt: inv.customer_tax_exempt ?? null,
    customerTaxIds: inv.customer_tax_ids ?? null,
    defaultPaymentMethod: strOrNull(inv.default_payment_method),
    defaultSource: strOrNull(inv.default_source),
    defaultTaxRates: inv.default_tax_rates ?? null,
    description: inv.description ?? null,
    discount: inv.discount ?? null,
    discounts: inv.discounts ?? null,
    dueDate: inv.due_date ?? null,
    effectiveAt: inv.effective_at ?? null,
    endingBalance: inv.ending_balance ?? null,
    footer: inv.footer ?? null,
    fromInvoice: inv.from_invoice ?? null,
    hostedInvoiceUrl: inv.hosted_invoice_url ?? null,
    invoicePdf: inv.invoice_pdf ?? null,
    issuer: inv.issuer ?? null,
    lastFinalizationError: inv.last_finalization_error ?? null,
    latestRevision: strOrNull(inv.latest_revision),
    livemode: inv.livemode,
    metadata: inv.metadata ?? null,
    nextPaymentAttempt: inv.next_payment_attempt ?? null,
    number: inv.number ?? null,
    onBehalfOf: strOrNull(inv.on_behalf_of),
    paid: inv.paid,
    paidOutOfBand: inv.paid_out_of_band,
    paymentIntent: strOrNull(inv.payment_intent),
    paymentSettings: inv.payment_settings ?? null,
    periodEnd: inv.period_end,
    periodStart: inv.period_start,
    postPaymentCreditNotesAmount: inv.post_payment_credit_notes_amount ?? null,
    prePaymentCreditNotesAmount: inv.pre_payment_credit_notes_amount ?? null,
    quote: strOrNull(inv.quote),
    receiptNumber: inv.receipt_number ?? null,
    rendering: inv.rendering ?? null,
    shippingCost: inv.shipping_cost ?? null,
    shippingDetails: inv.shipping_details ?? null,
    startingBalance: inv.starting_balance,
    statementDescriptor: inv.statement_descriptor ?? null,
    status: inv.status,
    statusTransitions: inv.status_transitions ?? null,
    subscription: strOrNull(inv.subscription),
    subscriptionDetails: inv.subscription_details ?? null,
    subtotal: inv.subtotal,
    subtotalExcludingTax: inv.subtotal_excluding_tax ?? null,
    tax: inv.tax ?? null,
    testClock: strOrNull(inv.test_clock),
    total: inv.total,
    totalDiscountAmounts: inv.total_discount_amounts ?? null,
    totalExcludingTax: inv.total_excluding_tax ?? null,
    totalTaxAmounts: inv.total_tax_amounts ?? null,
    transferData: inv.transfer_data ?? null,
    webhooksDeliveredAt: inv.webhooks_delivered_at ?? null,
    lastEventAt: eventCreated,
  };

  await db.insert(invoices).values(row).onConflictDoUpdate({
    target: invoices.id,
    set: {
      object: sql`excluded.object`,
      accountCountry: sql`excluded.account_country`,
      accountName: sql`excluded.account_name`,
      accountTaxIds: sql`excluded.account_tax_ids`,
      amountDue: sql`excluded.amount_due`,
      amountPaid: sql`excluded.amount_paid`,
      amountRemaining: sql`excluded.amount_remaining`,
      amountShipping: sql`excluded.amount_shipping`,
      application: sql`excluded.application`,
      applicationFeeAmount: sql`excluded.application_fee_amount`,
      attemptCount: sql`excluded.attempt_count`,
      attempted: sql`excluded.attempted`,
      autoAdvance: sql`excluded.auto_advance`,
      automaticTax: sql`excluded.automatic_tax`,
      billingReason: sql`excluded.billing_reason`,
      charge: sql`excluded.charge`,
      collectionMethod: sql`excluded.collection_method`,
      created: sql`excluded.created`,
      currency: sql`excluded.currency`,
      customFields: sql`excluded.custom_fields`,
      customer: sql`excluded.customer`,
      customerAddress: sql`excluded.customer_address`,
      customerEmail: sql`excluded.customer_email`,
      customerName: sql`excluded.customer_name`,
      customerPhone: sql`excluded.customer_phone`,
      customerShipping: sql`excluded.customer_shipping`,
      customerTaxExempt: sql`excluded.customer_tax_exempt`,
      customerTaxIds: sql`excluded.customer_tax_ids`,
      defaultPaymentMethod: sql`excluded.default_payment_method`,
      defaultSource: sql`excluded.default_source`,
      defaultTaxRates: sql`excluded.default_tax_rates`,
      description: sql`excluded.description`,
      discount: sql`excluded.discount`,
      discounts: sql`excluded.discounts`,
      dueDate: sql`excluded.due_date`,
      effectiveAt: sql`excluded.effective_at`,
      endingBalance: sql`excluded.ending_balance`,
      footer: sql`excluded.footer`,
      fromInvoice: sql`excluded.from_invoice`,
      hostedInvoiceUrl: sql`excluded.hosted_invoice_url`,
      invoicePdf: sql`excluded.invoice_pdf`,
      issuer: sql`excluded.issuer`,
      lastFinalizationError: sql`excluded.last_finalization_error`,
      latestRevision: sql`excluded.latest_revision`,
      livemode: sql`excluded.livemode`,
      metadata: sql`excluded.metadata`,
      nextPaymentAttempt: sql`excluded.next_payment_attempt`,
      number: sql`excluded.number`,
      onBehalfOf: sql`excluded.on_behalf_of`,
      paid: sql`excluded.paid`,
      paidOutOfBand: sql`excluded.paid_out_of_band`,
      paymentIntent: sql`excluded.payment_intent`,
      paymentSettings: sql`excluded.payment_settings`,
      periodEnd: sql`excluded.period_end`,
      periodStart: sql`excluded.period_start`,
      postPaymentCreditNotesAmount: sql`excluded.post_payment_credit_notes_amount`,
      prePaymentCreditNotesAmount: sql`excluded.pre_payment_credit_notes_amount`,
      quote: sql`excluded.quote`,
      receiptNumber: sql`excluded.receipt_number`,
      rendering: sql`excluded.rendering`,
      shippingCost: sql`excluded.shipping_cost`,
      shippingDetails: sql`excluded.shipping_details`,
      startingBalance: sql`excluded.starting_balance`,
      statementDescriptor: sql`excluded.statement_descriptor`,
      status: sql`excluded.status`,
      statusTransitions: sql`excluded.status_transitions`,
      subscription: sql`excluded.subscription`,
      subscriptionDetails: sql`excluded.subscription_details`,
      subtotal: sql`excluded.subtotal`,
      subtotalExcludingTax: sql`excluded.subtotal_excluding_tax`,
      tax: sql`excluded.tax`,
      testClock: sql`excluded.test_clock`,
      total: sql`excluded.total`,
      totalDiscountAmounts: sql`excluded.total_discount_amounts`,
      totalExcludingTax: sql`excluded.total_excluding_tax`,
      totalTaxAmounts: sql`excluded.total_tax_amounts`,
      transferData: sql`excluded.transfer_data`,
      webhooksDeliveredAt: sql`excluded.webhooks_delivered_at`,
      lastEventAt: sql`excluded.last_event_at`,
    },
    setWhere: sql`invoices.last_event_at < ${eventCreated}`,
  });

  for (const line of inv.lines?.data ?? []) {
    const lineRow = {
      id: line.id,
      object: line.object,
      amount: line.amount,
      amountExcludingTax: line.amount_excluding_tax ?? null,
      currency: line.currency,
      description: line.description ?? null,
      discountAmounts: line.discount_amounts ?? null,
      discountable: line.discountable,
      discounts: line.discounts ?? null,
      invoice: inv.id,
      invoiceItem: typeof line.invoice_item === 'string' ? line.invoice_item : null,
      livemode: line.livemode,
      metadata: line.metadata ?? null,
      period: line.period ?? null,
      plan: line.plan ?? null,
      price: line.price ?? null,
      proration: line.proration,
      prorationDetails: line.proration_details ?? null,
      quantity: line.quantity ?? null,
      subscription: typeof line.subscription === 'string' ? line.subscription : null,
      subscriptionItem: typeof line.subscription_item === 'string' ? line.subscription_item : null,
      taxAmounts: line.tax_amounts ?? null,
      taxRates: line.tax_rates ?? null,
      type: line.type,
      unitAmountExcludingTax: line.unit_amount_excluding_tax ?? null,
      lastEventAt: eventCreated,
    };
    await db.insert(invoiceLineItems).values(lineRow).onConflictDoUpdate({
      target: invoiceLineItems.id,
      set: {
        object: sql`excluded.object`,
        amount: sql`excluded.amount`,
        amountExcludingTax: sql`excluded.amount_excluding_tax`,
        currency: sql`excluded.currency`,
        description: sql`excluded.description`,
        discountAmounts: sql`excluded.discount_amounts`,
        discountable: sql`excluded.discountable`,
        discounts: sql`excluded.discounts`,
        invoice: sql`excluded.invoice`,
        invoiceItem: sql`excluded.invoice_item`,
        livemode: sql`excluded.livemode`,
        metadata: sql`excluded.metadata`,
        period: sql`excluded.period`,
        plan: sql`excluded.plan`,
        price: sql`excluded.price`,
        proration: sql`excluded.proration`,
        prorationDetails: sql`excluded.proration_details`,
        quantity: sql`excluded.quantity`,
        subscription: sql`excluded.subscription`,
        subscriptionItem: sql`excluded.subscription_item`,
        taxAmounts: sql`excluded.tax_amounts`,
        taxRates: sql`excluded.tax_rates`,
        type: sql`excluded.type`,
        unitAmountExcludingTax: sql`excluded.unit_amount_excluding_tax`,
        lastEventAt: sql`excluded.last_event_at`,
      },
      setWhere: sql`invoice_line_items.last_event_at < ${eventCreated}`,
    });
  }
}
